VERSION 0.7
ARG --global NODE_ALPINE_IMAGE=node:20-alpine

# Generic node alpine server. Just COPY your files and put your entrypoint in CMD
generic-node-alpine-server:
    # Port where your app will be running. This is required
    ARG --required APP_PORT

    FROM $NODE_ALPINE_IMAGE
    # Set the environment to production
    ENV NODE_ENV=production
    WORKDIR /app
    USER nobody
    ENTRYPOINT ["node"]
    EXPOSE $APP_PORT